### PR TITLE
MAINT: remove email actions workflow

### PR DESCRIPTION
**Pull request by anish-mudaraddi**
Moving email actions to use workflow structure instead
This allows us to remove `actions/email_workflows.py`

### CODE REVIEW

**Comment by anish-mudaraddi** [comment]
so this will need a rebase if #186 gets merged first (or vice versa)

**Review by DavidFair — APPROVED** [review]
Have we tested this against a dev instance?
If not, I'll try and squeeze in some testing tomorrow or Monday

**Comment by anish-mudaraddi** [comment]
I tested it before the submodule change - I'll test it again once #198 is merged

**Comment by anish-mudaraddi** [comment]
Yea looked like an extra fix was necessary - good call @DavidFair

**Comment by anish-mudaraddi** [comment]
Tested and working on dev with new bugfixes @DavidFair

**Review by Koldstream — APPROVED** [review]
Looks good! 👌

**Pull request merged**
